# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SequenceRun.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


"""
@author: Evan Larson, Hegeman & Cohen Labs - University of Minnesota
"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 220)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(471, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.StartSequence = QtWidgets.QPushButton(self.frame)
        self.StartSequence.setObjectName("StartSequence")
        self.verticalLayout.addWidget(self.StartSequence)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Starting Sequenced Run"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Confirm That All Dataset Folders Have a Config File! </p><p align=\"center\">It Must Be Generated and Saved From Main Program Window</p><p align=\"center\">And it must be saved as Config_(folder/dataset name).csv</p><p align=\"center\">Without Proper Config Files the Program Will Error</p><p align=\"center\">Check Readme for More Information</p><p align=\"center\"><span style=\" text-decoration: underline;\"><br/></span></p><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\"><br/></span></p></body></html>"))
        self.StartSequence.setText(_translate("Dialog", "Start Sequenced Run"))
